server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service

  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/identity_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

<<<<<<< HEAD
=======
outbound:
  identity:
    client-id: 850035654893-lft23uc6jkrs8u7l8t2svf8dfnbtpa4q.apps.googleusercontent.com
    client-secret: ${GOOGLE_CLIENT_SECRET:your_google_client_secret}
    redirect-uri: http://localhost:3000/authenticate

>>>>>>> c708287 (feat(oauth2): implement Authorization Code flow (FE code, Feign client, exchange token))
jwt:
  signerKey: XRHPndz7zeYl/OwDx3dXRmWJ6Xj199B//7vb9TtiIDJ2fGl4tkXbgbUnNrtZp2XG
  valid-duration: 3600 # in seconds
  refresh-valid-duration: 360000 # in seconds




