server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: XRHPndz7zeYl/OwDx3dXRmWJ6Xj199B//7vb9TtiIDJ2fGl4tkXbgbUnNrtZp2XG
  expiration: 3600000 # 1 hour in milliseconds




